server:
  port: ${PORT:8080}

spring:
#  profiles:
#    active: local
  mvc:
    cors:
      mappings:
        /api/**:
          allowed-origins: "https://codenewsfront.netlify.app/"
          allowed-methods: "*"
          allowed-headers: "*"
          allow-credentials: true

  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  kafka:
    bootstrap-servers: d1glerkdfulgj4bj265g.any.us-east-1.mpx.prd.cloud.redpanda.com:9092
    topic:
      news: codenews-news-v2
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-256
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="codenews-app" password="codenewsKafka2025!";
      ssl.endpoint.identification.algorithm: ""
    consumer:
      group-id: codenews-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    # tamanho do batch para envio de newsletter
    newsletter:
      batch:
        size: 10

scheduler:
  cron:
    # executa todo dia às 04:20
    daily: 0 20 04 * * *

app:
  scraper:
    rss-url: https://feeds2.feedburner.com/canaltechbr
  email:
    welcome:
      subject: "Bem-vindo ao CodeNews!"
