server:
  port: 8080

spring:
  mvc:
    cors:
      mappings:
        /api/**:
          allowed-origins: "http://localhost:3000"
          allowed-methods: "*"
          allowed-headers: "*"
          allow-credentials: true

  datasource:
    url: jdbc:postgresql://dpg-d1g072emcj7s73c6u030-a.oregon-postgres.render.com:5432/codenews_db?user=codenews_db_user&password=8umUffeczsKPDe7Ikpv8hGjecS3HfLC8
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: rafinhalvarenga@gmail.com
    password: nabj imtg sury vfcl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

  kafka:
    bootstrap-servers: d1glerkdfulgj4bj265g.any.us-east-1.mpx.prd.cloud.redpanda.com:9092
    topic:
      news: codenews-news-v2
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-256
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="codenews-app" password="codenewsKafka2025!";
      ssl.endpoint.identification.algorithm: ""
    consumer:
      group-id: codenews-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    # Tamanho de lote para newsletter (batch):
    newsletter:
      batch:
        size: 10

scheduler:
  cron:
    daily: 0 20 04 * * *

app:
  scraper:
    rss-url: "https://feeds2.feedburner.com/canaltechbr"
  email:
    welcome:
      subject: "Bem-vindo ao CodeNews!"