server:
  port: 8080

spring:
  mvc:
    cors:
      mappings:
        /api/**:
          allowed-origins: "http://localhost:3000"
          allowed-methods: "*"
          allowed-headers: "*"
          allow-credentials: true

  datasource:
    url: "${SPRING_DATASOURCE_URL}"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: rafinhalvarenga@gmail.com
    password: nabj imtg sury vfcl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

  kafka:
    bootstrap-servers: localhost:9092
    topic:
      news: codenews-news

    consumer:
      group-id: codenews-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    properties:
      spring:
        json:
          trusted:
            packages: org.codenews.model
          value:
            default:
              type: org.codenews.model.News

    # Tamanho de lote para newsletter (batch):
    newsletter:
      batch:
        size: 10

scheduler:
  cron:
    daily: 0 20 04 * * *

app:
  scraper:
    rss-url: "https://feeds2.feedburner.com/canaltechbr"
  email:
    welcome:
      subject: "Bem-vindo ao CodeNews!"