server:
  # Railway define a porta via ENV var PORT
  port: ${PORT:8080}

spring:
  mvc:
    cors:
      mappings:
        /api/**:
          # URL do front-end (ex: sua app Vercel). Defina FRONTEND_URL no Railway.
          allowed-origins: "${FRONTEND_URL}"
          allowed-methods: "*"
          allowed-headers: "*"
          allow-credentials: true

  datasource:
    # Railway expõe DATABASE_URL (jdbc://user:pass@host:port/db)
      url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
      username: ${PGUSER}
      password: ${PGPASSWORD}
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # Em produção, não recriar esquema automaticamente
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    topic:
      # Exemplo: defina KAFKA_TOPIC_NEWS ou use o padrão
      news: ${KAFKA_TOPIC_NEWS:codenews-news}

    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:codenews-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    properties:
      spring:
        json:
          trusted:
            packages: org.codenews.model
          value:
            default:
              type: org.codenews.model.News

    newsletter:
      batch:
        size: ${NEWSLETTER_BATCH_SIZE:10}

scheduler:
  cron:
    # Se quiser alterar o horário, basta mudar esta ENV
    daily: ${SCHEDULER_CRON_DAILY:0 20 04 * * *}

app:
  scraper:
    # URL do RSS — também pode vir de ENV
    rss-url: ${SCRAPER_RSS_URL:https://feeds2.feedburner.com/canaltechbr}
  email:
    welcome:
      subject: ${EMAIL_WELCOME_SUBJECT:Bem-vindo ao CodeNews!}
